#!/bin/bash

echo "🎹 MIDI AI Factory - Guide de démarrage rapide"
echo "=============================================="
echo ""
echo "1️⃣  INSTALLATION DE L'ENVIRONNEMENT:"
echo "   conda env create -f environment.yml"
echo "   conda activate midi-ai"
echo ""
echo "2️⃣  VÉRIFICATION MPS (Apple Silicon):"
echo "   python -c 'import torch; print(f\"MPS disponible: {torch.backends.mps.is_available()}\")''"
echo ""
echo "3️⃣  LANCEMENT DU PIPELINE COMPLET:"
echo "   python main.py all --epochs 50"
echo ""
echo "   Ou étape par étape:"
echo "   python main.py analyze    # Analyser les MIDIs"
echo "   python main.py tokenize   # Tokenizer"
echo "   python main.py train      # Entraîner"
echo "   python main.py generate   # Générer"
echo ""
echo "4️⃣  GÉNÉRATION RAPIDE (après entraînement):"
echo "   python generate.py --n-clips 10 --style random"
echo ""
echo "📁 Les fichiers générés seront dans ./output_midi/"
echo ""